GET http://localhost:3000/Usuarios
content-type: application/json; charset=utf-8



POST http://localhost:3000/Usuarios
content-type: application/json; charset=utf-8
{

"id":"5", 
"name":"Peter",
"email":"Peter@gmail.com",
"role":"admin",
"age":"25"

}